### ISSUE TITLE
text align in tips

### ISSUE THREAD

**Issue by kfa1983** [jaz303/tipsy#94]
Dear all,

Here's an easy practice to add the text-align option to your tipsy :

in jquery.tipsy.js search for :

< div class="tipsy-arrow" >< /div >< div class="tipsy-inner" >< /div >

and replace with :

< div class="tipsy-arrow" >< /div >< div class="tipsy-inner" style="text-align:'+this.options.align+'" >< /div >

then, go to $.fn.tipsy.defaults, and add : align: center,

Default is center.

Use : $('.myDiv').tipsy({align: 'center'}); // 'center', 'left', 'right', 'justify'

You can also edit your CSS and remove / comment the text-align from tispy .inner.

Cheers

**Comment by Mottie** [comment]
You can also do this wIthout modifying the plugin:

CSS

``` css
.center .tipsy-inner { text-align: center; }
.left .tipsy-inner { text-align: left; }
.right .tipsy-inner { text-align: right; }
```

Script

``` javascript
$('.myDiv').tipsy({
   className: "right"
});
```
